[2022-12-28T04:53:23.542+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.serve_bentoml manual__2022-12-28T04:44:13.296482+00:00 [queued]>
[2022-12-28T04:53:23.555+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.serve_bentoml manual__2022-12-28T04:44:13.296482+00:00 [queued]>
[2022-12-28T04:53:23.555+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T04:53:23.555+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-28T04:53:23.556+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T04:53:23.576+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): serve_bentoml> on 2022-12-28 04:44:13.296482+00:00
[2022-12-28T04:53:23.590+0000] {standard_task_runner.py:54} INFO - Started process 837 to run task
[2022-12-28T04:53:23.597+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bertopic_autopik_***', 'serve_bentoml', 'manual__2022-12-28T04:44:13.296482+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/bertopic_autopik_***.py', '--cfg-path', '/tmp/tmpu0qp0sp4']
[2022-12-28T04:53:23.599+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask serve_bentoml
[2022-12-28T04:53:23.601+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/bertopic_autopik_***.py
[2022-12-28T04:53:35.598+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-28T04:53:35.673+0000] {task_command.py:384} INFO - Running <TaskInstance: bertopic_autopik_airflow.serve_bentoml manual__2022-12-28T04:44:13.296482+00:00 [running]> on host 2f95ab99defd
[2022-12-28T04:53:35.752+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hojun.seo@pikurate.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bertopic_autopik_***
AIRFLOW_CTX_TASK_ID=serve_bentoml
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T04:44:13.296482+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-28T04:44:13.296482+00:00
[2022-12-28T04:53:35.753+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-28T04:53:35.754+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n            fuser -k 7171/tcp; bentoml serve -p 7171 bertopic_autopik_bento:latest --production\n        ']
[2022-12-28T04:53:35.788+0000] {subprocess.py:86} INFO - Output:
[2022-12-28T04:54:01.816+0000] {subprocess.py:93} INFO - 2022-12-28T04:54:01+0000 [INFO] [cli] Environ for worker 0: set CUDA_VISIBLE_DEVICES to 0
[2022-12-28T04:54:01.829+0000] {subprocess.py:93} INFO - 2022-12-28T04:54:01+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "bertopic_autopik_bento:latest" can be accessed at http://localhost:7171/metrics.
[2022-12-28T04:54:03.275+0000] {subprocess.py:93} INFO - 2022-12-28T04:54:03+0000 [ERROR] [cli] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7fbf5392dd00>>
[2022-12-28T04:54:03.275+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:03.275+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/circus/util.py", line 1126, in _run
[2022-12-28T04:54:03.276+0000] {subprocess.py:93} INFO -     val = self.callback()
[2022-12-28T04:54:03.276+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/circus/util.py", line 1038, in wrapper
[2022-12-28T04:54:03.276+0000] {subprocess.py:93} INFO -     raise ConflictError("arbiter is already running %s command"
[2022-12-28T04:54:03.276+0000] {subprocess.py:93} INFO - circus.exc.ConflictError: arbiter is already running arbiter_start_watchers command
[2022-12-28T04:54:04.326+0000] {subprocess.py:93} INFO - 2022-12-28T04:54:04+0000 [ERROR] [cli] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7fbf5392dd00>>
[2022-12-28T04:54:04.326+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:04.326+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/circus/util.py", line 1126, in _run
[2022-12-28T04:54:04.327+0000] {subprocess.py:93} INFO -     val = self.callback()
[2022-12-28T04:54:04.327+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/circus/util.py", line 1038, in wrapper
[2022-12-28T04:54:04.327+0000] {subprocess.py:93} INFO -     raise ConflictError("arbiter is already running %s command"
[2022-12-28T04:54:04.327+0000] {subprocess.py:93} INFO - circus.exc.ConflictError: arbiter is already running arbiter_start_watchers command
[2022-12-28T04:54:04.327+0000] {subprocess.py:93} INFO - 2022-12-28T04:54:04+0000 [INFO] [cli] Starting production HTTP BentoServer from "bertopic_autopik_bento:latest" listening on http://0.0.0.0:7171 (Press CTRL+C to quit)
[2022-12-28T04:54:36.987+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:36.988+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:36.988+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:36.989+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:36.989+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:36.989+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:36.989+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:36.989+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:36.990+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 359, in load
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 139, in import_service
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO -     raise ImportServiceError(f'Failed to import module "{module_name}": {e}')
[2022-12-28T04:54:36.991+0000] {subprocess.py:93} INFO - bentoml.exceptions.ImportServiceError: Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:36.992+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:36.992+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:36.992+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:36.992+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:36.992+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -     return _run_code(code, main_globals, None,
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -     exec(code, run_globals)
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 180, in <module>
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -     main()  # pylint: disable=no-value-for-parameter
[2022-12-28T04:54:36.993+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2022-12-28T04:54:36.994+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 127, in main
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -     svc = bentoml.load(bento_identifier, working_dir=working_dir, standalone_load=True)
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 368, in load
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -     svc = load_bento(bento_identifier, standalone_load=standalone_load)
[2022-12-28T04:54:36.995+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 221, in load_bento
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -     return _load_bento(bento, standalone_load)
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 247, in _load_bento
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:36.996+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:36.997+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -   File "/root/bentoml/bentos/bertopic_autopik_bento/rtd2f4egno6h2asc/src/bento_service_auto_pik.py", line 67, in <module>
[2022-12-28T04:54:36.998+0000] {subprocess.py:93} INFO -     model = BERTopic.load("/opt/***/dags/data/bertopic_paraphrase-multilingual-MiniLM-L12-v2_40_20")
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2197, in load
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -     topic_model = joblib.load(file)
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -     obj = _unpickle(fobj)
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
[2022-12-28T04:54:36.999+0000] {subprocess.py:93} INFO -     obj = unpickler.load()
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -     dispatch[key[0]](self)
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1589, in load_reduce
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -     stack[-1] = func(*args)
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/storage.py", line 240, in _load_from_bytes
[2022-12-28T04:54:37.000+0000] {subprocess.py:93} INFO -     return torch.load(io.BytesIO(b))
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 1012, in _legacy_load
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -     result = unpickler.load()
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 958, in persistent_load
[2022-12-28T04:54:37.001+0000] {subprocess.py:93} INFO -     wrap_storage=restore_location(obj, location),
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO -     result = fn(storage, location)
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO -     return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO - RuntimeError: CUDA error: out of memory
[2022-12-28T04:54:37.002+0000] {subprocess.py:93} INFO - CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[2022-12-28T04:54:37.003+0000] {subprocess.py:93} INFO - For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-12-28T04:54:37.003+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:37.003+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:37.013+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:37.014+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:37.014+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:37.015+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:37.016+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:37.016+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:37.016+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 359, in load
[2022-12-28T04:54:37.016+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:37.016+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 139, in import_service
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO -     raise ImportServiceError(f'Failed to import module "{module_name}": {e}')
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO - bentoml.exceptions.ImportServiceError: Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:37.017+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:37.018+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:37.018+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:37.018+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-12-28T04:54:37.018+0000] {subprocess.py:93} INFO -     return _run_code(code, main_globals, None,
[2022-12-28T04:54:37.018+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
[2022-12-28T04:54:37.019+0000] {subprocess.py:93} INFO -     exec(code, run_globals)
[2022-12-28T04:54:37.019+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 180, in <module>
[2022-12-28T04:54:37.019+0000] {subprocess.py:93} INFO -     main()  # pylint: disable=no-value-for-parameter
[2022-12-28T04:54:37.019+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2022-12-28T04:54:37.020+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2022-12-28T04:54:37.020+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2022-12-28T04:54:37.020+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2022-12-28T04:54:37.020+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2022-12-28T04:54:37.021+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2022-12-28T04:54:37.021+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2022-12-28T04:54:37.021+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2022-12-28T04:54:37.021+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 127, in main
[2022-12-28T04:54:37.022+0000] {subprocess.py:93} INFO -     svc = bentoml.load(bento_identifier, working_dir=working_dir, standalone_load=True)
[2022-12-28T04:54:37.022+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 368, in load
[2022-12-28T04:54:37.022+0000] {subprocess.py:93} INFO -     svc = load_bento(bento_identifier, standalone_load=standalone_load)
[2022-12-28T04:54:37.022+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:37.023+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:37.023+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 221, in load_bento
[2022-12-28T04:54:37.023+0000] {subprocess.py:93} INFO -     return _load_bento(bento, standalone_load)
[2022-12-28T04:54:37.023+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 247, in _load_bento
[2022-12-28T04:54:37.023+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:37.024+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:37.024+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:37.024+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:37.024+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2022-12-28T04:54:37.025+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-12-28T04:54:37.026+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-12-28T04:54:37.026+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-28T04:54:37.026+0000] {subprocess.py:93} INFO -   File "/root/bentoml/bentos/bertopic_autopik_bento/rtd2f4egno6h2asc/src/bento_service_auto_pik.py", line 67, in <module>
[2022-12-28T04:54:37.026+0000] {subprocess.py:93} INFO -     model = BERTopic.load("/opt/***/dags/data/bertopic_paraphrase-multilingual-MiniLM-L12-v2_40_20")
[2022-12-28T04:54:37.026+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2197, in load
[2022-12-28T04:54:37.027+0000] {subprocess.py:93} INFO -     topic_model = joblib.load(file)
[2022-12-28T04:54:37.027+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
[2022-12-28T04:54:37.027+0000] {subprocess.py:93} INFO -     obj = _unpickle(fobj)
[2022-12-28T04:54:37.027+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
[2022-12-28T04:54:37.028+0000] {subprocess.py:93} INFO -     obj = unpickler.load()
[2022-12-28T04:54:37.028+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
[2022-12-28T04:54:37.028+0000] {subprocess.py:93} INFO -     dispatch[key[0]](self)
[2022-12-28T04:54:37.028+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1589, in load_reduce
[2022-12-28T04:54:37.028+0000] {subprocess.py:93} INFO -     stack[-1] = func(*args)
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/storage.py", line 240, in _load_from_bytes
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -     return torch.load(io.BytesIO(b))
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 1012, in _legacy_load
[2022-12-28T04:54:37.029+0000] {subprocess.py:93} INFO -     result = unpickler.load()
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 958, in persistent_load
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -     wrap_storage=restore_location(obj, location),
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -     result = fn(storage, location)
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
[2022-12-28T04:54:37.030+0000] {subprocess.py:93} INFO -     return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
[2022-12-28T04:54:37.031+0000] {subprocess.py:93} INFO - RuntimeError: CUDA error: out of memory
[2022-12-28T04:54:37.031+0000] {subprocess.py:93} INFO - CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[2022-12-28T04:54:37.031+0000] {subprocess.py:93} INFO - For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-12-28T04:54:40.033+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:40.039+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:40.039+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:40.039+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:40.040+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:40.040+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:40.041+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:40.041+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[2022-12-28T04:54:40.041+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:40.042+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:40.042+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:40.042+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:40.043+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:40.043+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 359, in load
[2022-12-28T04:54:40.043+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:40.044+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:40.044+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:40.044+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 139, in import_service
[2022-12-28T04:54:40.045+0000] {subprocess.py:93} INFO -     raise ImportServiceError(f'Failed to import module "{module_name}": {e}')
[2022-12-28T04:54:40.045+0000] {subprocess.py:93} INFO - bentoml.exceptions.ImportServiceError: Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento'
[2022-12-28T04:54:40.045+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:40.046+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:54:40.046+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:54:40.047+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:54:40.052+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-12-28T04:54:40.052+0000] {subprocess.py:93} INFO -     return _run_code(code, main_globals, None,
[2022-12-28T04:54:40.053+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
[2022-12-28T04:54:40.053+0000] {subprocess.py:93} INFO -     exec(code, run_globals)
[2022-12-28T04:54:40.053+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 180, in <module>
[2022-12-28T04:54:40.054+0000] {subprocess.py:93} INFO -     main()  # pylint: disable=no-value-for-parameter
[2022-12-28T04:54:40.054+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2022-12-28T04:54:40.054+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2022-12-28T04:54:40.087+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2022-12-28T04:54:40.087+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2022-12-28T04:54:40.088+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2022-12-28T04:54:40.088+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2022-12-28T04:54:40.088+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2022-12-28T04:54:40.089+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2022-12-28T04:54:40.089+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 127, in main
[2022-12-28T04:54:40.089+0000] {subprocess.py:93} INFO -     svc = bentoml.load(bento_identifier, working_dir=working_dir, standalone_load=True)
[2022-12-28T04:54:40.089+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 368, in load
[2022-12-28T04:54:40.090+0000] {subprocess.py:93} INFO -     svc = load_bento(bento_identifier, standalone_load=standalone_load)
[2022-12-28T04:54:40.090+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:40.103+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:40.103+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 221, in load_bento
[2022-12-28T04:54:40.104+0000] {subprocess.py:93} INFO -     return _load_bento(bento, standalone_load)
[2022-12-28T04:54:40.104+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 247, in _load_bento
[2022-12-28T04:54:40.105+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:54:40.105+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:54:40.108+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:54:40.126+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:54:40.126+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:54:40.127+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:54:40.127+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:54:40.127+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:54:40.128+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:54:40.128+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2022-12-28T04:54:40.128+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-12-28T04:54:40.129+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-12-28T04:54:40.129+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-28T04:54:40.129+0000] {subprocess.py:93} INFO -   File "/root/bentoml/bentos/bertopic_autopik_bento/rtd2f4egno6h2asc/src/bento_service_auto_pik.py", line 67, in <module>
[2022-12-28T04:54:40.130+0000] {subprocess.py:93} INFO -     model = BERTopic.load("/opt/***/dags/data/bertopic_paraphrase-multilingual-MiniLM-L12-v2_40_20")
[2022-12-28T04:54:40.130+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2197, in load
[2022-12-28T04:54:40.130+0000] {subprocess.py:93} INFO -     topic_model = joblib.load(file)
[2022-12-28T04:54:40.130+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
[2022-12-28T04:54:40.131+0000] {subprocess.py:93} INFO -     obj = _unpickle(fobj)
[2022-12-28T04:54:40.131+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
[2022-12-28T04:54:40.131+0000] {subprocess.py:93} INFO -     obj = unpickler.load()
[2022-12-28T04:54:40.132+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
[2022-12-28T04:54:40.132+0000] {subprocess.py:93} INFO -     dispatch[key[0]](self)
[2022-12-28T04:54:40.132+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1589, in load_reduce
[2022-12-28T04:54:40.133+0000] {subprocess.py:93} INFO -     stack[-1] = func(*args)
[2022-12-28T04:54:40.133+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/storage.py", line 240, in _load_from_bytes
[2022-12-28T04:54:40.133+0000] {subprocess.py:93} INFO -     return torch.load(io.BytesIO(b))
[2022-12-28T04:54:40.134+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
[2022-12-28T04:54:40.144+0000] {subprocess.py:93} INFO -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
[2022-12-28T04:54:40.145+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 1012, in _legacy_load
[2022-12-28T04:54:40.145+0000] {subprocess.py:93} INFO -     result = unpickler.load()
[2022-12-28T04:54:40.145+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 958, in persistent_load
[2022-12-28T04:54:40.145+0000] {subprocess.py:93} INFO -     wrap_storage=restore_location(obj, location),
[2022-12-28T04:54:40.146+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
[2022-12-28T04:54:40.146+0000] {subprocess.py:93} INFO -     result = fn(storage, location)
[2022-12-28T04:54:40.147+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
[2022-12-28T04:54:40.147+0000] {subprocess.py:93} INFO -     return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
[2022-12-28T04:54:40.147+0000] {subprocess.py:93} INFO - RuntimeError: CUDA error: out of memory
[2022-12-28T04:54:40.148+0000] {subprocess.py:93} INFO - CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[2022-12-28T04:54:40.148+0000] {subprocess.py:93} INFO - For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-12-28T04:55:21.266+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.310+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:55:21.310+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:55:21.311+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:55:21.311+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:55:21.312+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:55:21.312+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:55:21.312+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[2022-12-28T04:55:21.313+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'bertopic_autopik_bento'
[2022-12-28T04:55:21.313+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.313+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:55:21.313+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.348+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.348+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 359, in load
[2022-12-28T04:55:21.349+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:55:21.349+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.349+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.350+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 139, in import_service
[2022-12-28T04:55:21.350+0000] {subprocess.py:93} INFO -     raise ImportServiceError(f'Failed to import module "{module_name}": {e}')
[2022-12-28T04:55:21.350+0000] {subprocess.py:93} INFO - bentoml.exceptions.ImportServiceError: Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento'
[2022-12-28T04:55:21.351+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.351+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:55:21.351+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.351+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.352+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-12-28T04:55:21.352+0000] {subprocess.py:93} INFO -     return _run_code(code, main_globals, None,
[2022-12-28T04:55:21.352+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
[2022-12-28T04:55:21.353+0000] {subprocess.py:93} INFO -     exec(code, run_globals)
[2022-12-28T04:55:21.353+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 180, in <module>
[2022-12-28T04:55:21.353+0000] {subprocess.py:93} INFO -     main()  # pylint: disable=no-value-for-parameter
[2022-12-28T04:55:21.353+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2022-12-28T04:55:21.409+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2022-12-28T04:55:21.410+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2022-12-28T04:55:21.410+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2022-12-28T04:55:21.410+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2022-12-28T04:55:21.410+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2022-12-28T04:55:21.411+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2022-12-28T04:55:21.411+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2022-12-28T04:55:21.411+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 127, in main
[2022-12-28T04:55:21.412+0000] {subprocess.py:93} INFO -     svc = bentoml.load(bento_identifier, working_dir=working_dir, standalone_load=True)
[2022-12-28T04:55:21.412+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 368, in load
[2022-12-28T04:55:21.412+0000] {subprocess.py:93} INFO -     svc = load_bento(bento_identifier, standalone_load=standalone_load)
[2022-12-28T04:55:21.413+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.413+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.413+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 221, in load_bento
[2022-12-28T04:55:21.413+0000] {subprocess.py:93} INFO -     return _load_bento(bento, standalone_load)
[2022-12-28T04:55:21.414+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 247, in _load_bento
[2022-12-28T04:55:21.524+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:55:21.525+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.525+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.526+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:55:21.526+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:55:21.526+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:55:21.527+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:55:21.527+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:55:21.527+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:55:21.528+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2022-12-28T04:55:21.528+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-12-28T04:55:21.528+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-12-28T04:55:21.529+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-28T04:55:21.529+0000] {subprocess.py:93} INFO -   File "/root/bentoml/bentos/bertopic_autopik_bento/rtd2f4egno6h2asc/src/bento_service_auto_pik.py", line 67, in <module>
[2022-12-28T04:55:21.529+0000] {subprocess.py:93} INFO -     model = BERTopic.load("/opt/***/dags/data/bertopic_paraphrase-multilingual-MiniLM-L12-v2_40_20")
[2022-12-28T04:55:21.530+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2197, in load
[2022-12-28T04:55:21.579+0000] {subprocess.py:93} INFO -     topic_model = joblib.load(file)
[2022-12-28T04:55:21.580+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
[2022-12-28T04:55:21.580+0000] {subprocess.py:93} INFO -     obj = _unpickle(fobj)
[2022-12-28T04:55:21.581+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
[2022-12-28T04:55:21.581+0000] {subprocess.py:93} INFO -     obj = unpickler.load()
[2022-12-28T04:55:21.581+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
[2022-12-28T04:55:21.582+0000] {subprocess.py:93} INFO -     dispatch[key[0]](self)
[2022-12-28T04:55:21.582+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1589, in load_reduce
[2022-12-28T04:55:21.582+0000] {subprocess.py:93} INFO -     stack[-1] = func(*args)
[2022-12-28T04:55:21.610+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/storage.py", line 240, in _load_from_bytes
[2022-12-28T04:55:21.610+0000] {subprocess.py:93} INFO -     return torch.load(io.BytesIO(b))
[2022-12-28T04:55:21.611+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
[2022-12-28T04:55:21.611+0000] {subprocess.py:93} INFO -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
[2022-12-28T04:55:21.611+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 1012, in _legacy_load
[2022-12-28T04:55:21.612+0000] {subprocess.py:93} INFO -     result = unpickler.load()
[2022-12-28T04:55:21.612+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 958, in persistent_load
[2022-12-28T04:55:21.612+0000] {subprocess.py:93} INFO -     wrap_storage=restore_location(obj, location),
[2022-12-28T04:55:21.613+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
[2022-12-28T04:55:21.613+0000] {subprocess.py:93} INFO -     result = fn(storage, location)
[2022-12-28T04:55:21.613+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
[2022-12-28T04:55:21.614+0000] {subprocess.py:93} INFO -     return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
[2022-12-28T04:55:21.637+0000] {subprocess.py:93} INFO - RuntimeError: CUDA error: out of memory
[2022-12-28T04:55:21.638+0000] {subprocess.py:93} INFO - CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[2022-12-28T04:55:21.638+0000] {subprocess.py:93} INFO - For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-12-28T04:55:21.643+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.643+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:55:21.644+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'bertopic_autopik_bento'
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 359, in load
[2022-12-28T04:55:21.645+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 139, in import_service
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO -     raise ImportServiceError(f'Failed to import module "{module_name}": {e}')
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO - bentoml.exceptions.ImportServiceError: Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento'
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.646+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2022-12-28T04:55:21.647+0000] {subprocess.py:93} INFO - 
[2022-12-28T04:55:21.647+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-28T04:55:21.647+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-12-28T04:55:21.647+0000] {subprocess.py:93} INFO -     return _run_code(code, main_globals, None,
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -     exec(code, run_globals)
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 180, in <module>
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -     main()  # pylint: disable=no-value-for-parameter
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2022-12-28T04:55:21.653+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2022-12-28T04:55:21.654+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml_cli/worker/http_api_server.py", line 127, in main
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -     svc = bentoml.load(bento_identifier, working_dir=working_dir, standalone_load=True)
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 368, in load
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -     svc = load_bento(bento_identifier, standalone_load=standalone_load)
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 221, in load_bento
[2022-12-28T04:55:21.655+0000] {subprocess.py:93} INFO -     return _load_bento(bento, standalone_load)
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 247, in _load_bento
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -     svc = import_service(
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_name, package=working_dir)
[2022-12-28T04:55:21.656+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-12-28T04:55:21.657+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -   File "/root/bentoml/bentos/bertopic_autopik_bento/rtd2f4egno6h2asc/src/bento_service_auto_pik.py", line 67, in <module>
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -     model = BERTopic.load("/opt/***/dags/data/bertopic_paraphrase-multilingual-MiniLM-L12-v2_40_20")
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2197, in load
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -     topic_model = joblib.load(file)
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
[2022-12-28T04:55:21.658+0000] {subprocess.py:93} INFO -     obj = _unpickle(fobj)
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -     obj = unpickler.load()
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -     dispatch[key[0]](self)
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pickle.py", line 1589, in load_reduce
[2022-12-28T04:55:21.659+0000] {subprocess.py:93} INFO -     stack[-1] = func(*args)
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/storage.py", line 240, in _load_from_bytes
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -     return torch.load(io.BytesIO(b))
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 1012, in _legacy_load
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -     result = unpickler.load()
[2022-12-28T04:55:21.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 958, in persistent_load
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO -     wrap_storage=restore_location(obj, location),
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO -     result = fn(storage, location)
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/torch/serialization.py", line 185, in _cuda_deserialize
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO -     return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO - RuntimeError: CUDA error: out of memory
[2022-12-28T04:55:21.661+0000] {subprocess.py:93} INFO - CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[2022-12-28T04:55:21.662+0000] {subprocess.py:93} INFO - For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-12-28T04:58:16.850+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-12-28T04:58:16.861+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 837. PIDs of all processes in the group: [858, 860, 908, 915, 917, 919, 925, 931, 932, 939, 959, 1837, 2034, 2036, 2038, 2059, 2118, 2211, 2295, 2322, 2331, 2376, 2437, 837]
[2022-12-28T04:58:16.862+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 837
[2022-12-28T04:58:16.864+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-28T04:58:16.865+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-28T04:58:17.164+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 20 for task serve_bentoml ((psycopg2.OperationalError) connection to server at "postgres" (172.18.0.2), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8); 837)
[2022-12-28T04:58:17.291+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2376, status='terminated', started='04:58:04') (2376) terminated with exit code None
[2022-12-28T04:58:17.293+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2437, status='terminated', started='04:58:14') (2437) terminated with exit code None
[2022-12-28T04:58:17.498+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2331, status='terminated', started='04:57:55') (2331) terminated with exit code None
[2022-12-28T04:58:17.501+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=858, status='terminated', started='04:53:35') (858) terminated with exit code None
[2022-12-28T04:58:17.725+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2322, status='terminated', started='04:57:46') (2322) terminated with exit code None
[2022-12-28T04:58:17.941+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2118, status='terminated', started='04:57:12') (2118) terminated with exit code None
[2022-12-28T04:58:17.942+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2295, status='terminated', started='04:57:40') (2295) terminated with exit code None
[2022-12-28T04:58:17.996+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=837, status='terminated', exitcode=1, started='04:53:23') (837) terminated with exit code 1
[2022-12-28T04:58:18.296+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2034, status='terminated', started='04:56:51') (2034) terminated with exit code None
[2022-12-28T04:58:18.297+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2059, status='terminated', started='04:57:08') (2059) terminated with exit code None
[2022-12-28T04:58:18.391+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2211, status='terminated', started='04:57:21') (2211) terminated with exit code None
[2022-12-28T04:58:18.445+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1837, status='terminated', started='04:56:17') (1837) terminated with exit code None
[2022-12-28T04:58:18.447+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2038, status='terminated', started='04:57:03') (2038) terminated with exit code None
[2022-12-28T04:58:18.502+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2036, status='terminated', started='04:56:55') (2036) terminated with exit code None
