[2022-12-27T09:16:49.957+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.serve_bentoml scheduled__2022-12-27T06:00:00+00:00 [queued]>
[2022-12-27T09:16:49.972+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.serve_bentoml scheduled__2022-12-27T06:00:00+00:00 [queued]>
[2022-12-27T09:16:49.972+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T09:16:49.972+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-27T09:16:49.973+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T09:16:49.991+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): serve_bentoml> on 2022-12-27 06:00:00+00:00
[2022-12-27T09:16:49.999+0000] {standard_task_runner.py:54} INFO - Started process 365 to run task
[2022-12-27T09:16:50.003+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bertopic_autopik_***', 'serve_bentoml', 'scheduled__2022-12-27T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/bertopic_autopik_***.py', '--cfg-path', '/tmp/tmpqdoo0wzu']
[2022-12-27T09:16:50.004+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask serve_bentoml
[2022-12-27T09:16:50.005+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/bertopic_autopik_***.py
[2022-12-27T09:17:03.415+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-27T09:17:03.510+0000] {task_command.py:384} INFO - Running <TaskInstance: bertopic_autopik_airflow.serve_bentoml scheduled__2022-12-27T06:00:00+00:00 [running]> on host a0f3911d9707
[2022-12-27T09:17:03.625+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hojun.seo@pikurate.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bertopic_autopik_***
AIRFLOW_CTX_TASK_ID=serve_bentoml
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T06:00:00+00:00
[2022-12-27T09:17:03.627+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-27T09:17:03.628+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n            fuser -k 7171/tcp; bentoml serve -p 7171 bertopic_autopik_bento:latest --production\n        ']
[2022-12-27T09:17:03.685+0000] {subprocess.py:86} INFO - Output:
[2022-12-27T09:17:05.284+0000] {subprocess.py:93} INFO - Error: [bentoml-cli] `serve` failed: Failed to load bento or import service 'bertopic_autopik_bento:latest'.
[2022-12-27T09:17:05.284+0000] {subprocess.py:93} INFO - If you are attempting to import bento in local store: 'Failed to import module "bertopic_autopik_bento": No module named 'bertopic_autopik_bento''.
[2022-12-27T09:17:05.284+0000] {subprocess.py:93} INFO - If you are importing by python module path: 'no Bentos with name 'bertopic_autopik_bento' exist in BentoML store <osfs '/root/bentoml/bentos'>'.
[2022-12-27T09:17:05.437+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-27T09:17:05.460+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-27T09:17:05.466+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=bertopic_autopik_***, task_id=serve_bentoml, execution_date=20221227T060000, start_date=20221227T091649, end_date=20221227T091705
[2022-12-27T09:17:05.883+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 8 for task serve_bentoml (Bash command failed. The command returned a non-zero exit code 1.; 365)
[2022-12-27T09:17:06.030+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-27T09:17:06.069+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
