[2022-12-26T07:11:27.074+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.db_data_fetching scheduled__2022-12-26T04:00:00+00:00 [queued]>
[2022-12-26T07:11:27.089+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bertopic_autopik_airflow.db_data_fetching scheduled__2022-12-26T04:00:00+00:00 [queued]>
[2022-12-26T07:11:27.089+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T07:11:27.089+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-26T07:11:27.089+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T07:11:27.108+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): db_data_fetching> on 2022-12-26 04:00:00+00:00
[2022-12-26T07:11:27.116+0000] {standard_task_runner.py:54} INFO - Started process 95 to run task
[2022-12-26T07:11:27.120+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bertopic_autopik_***', 'db_data_fetching', 'scheduled__2022-12-26T04:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/bertopic_autopik_***.py', '--cfg-path', '/tmp/tmpc9uz_co0']
[2022-12-26T07:11:27.121+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask db_data_fetching
[2022-12-26T07:11:27.122+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/bertopic_autopik_***.py
[2022-12-26T07:11:40.359+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-26T07:11:40.416+0000] {task_command.py:384} INFO - Running <TaskInstance: bertopic_autopik_airflow.db_data_fetching scheduled__2022-12-26T04:00:00+00:00 [running]> on host c4b524c24ec1
[2022-12-26T07:11:40.494+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hojun.seo@pikurate.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bertopic_autopik_***
AIRFLOW_CTX_TASK_ID=db_data_fetching
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T04:00:00+00:00
[2022-12-26T07:13:50.435+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/data.py", line 145, in db_data_fetching
    conn = psycopg2.connect(host=hostname, dbname=dbname, user=username, password=password, port=portnumber)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "dev-postgres.c5dkkbujxodg.ap-northeast-2.rds.amazonaws.com" (10.2.3.66), port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2022-12-26T07:13:50.457+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=bertopic_autopik_***, task_id=db_data_fetching, execution_date=20221226T040000, start_date=20221226T071127, end_date=20221226T071350
[2022-12-26T07:13:50.827+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 3 for task db_data_fetching (connection to server at "dev-postgres.c5dkkbujxodg.ap-northeast-2.rds.amazonaws.com" (10.2.3.66), port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 95)
[2022-12-26T07:13:50.972+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-26T07:13:51.070+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
