[2022-12-28T01:11:19.500+0000] {processor.py:156} INFO - Started process (PID=114) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:11:19.501+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:11:19.502+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:11:19.502+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:11:30.025+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:11:30.023+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:11:30.026+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:11:30.074+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 10.578 seconds
[2022-12-28T01:12:03.000+0000] {processor.py:156} INFO - Started process (PID=227) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:03.003+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:12:03.005+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:12:03.004+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:15.327+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:12:15.321+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:12:15.327+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:15.373+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.391 seconds
[2022-12-28T01:12:45.774+0000] {processor.py:156} INFO - Started process (PID=336) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:45.784+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:12:45.784+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:12:45.784+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:58.124+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:12:58.122+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:12:58.125+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:12:58.157+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.387 seconds
[2022-12-28T01:13:28.447+0000] {processor.py:156} INFO - Started process (PID=445) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:13:28.459+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:13:28.461+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:13:28.461+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:13:39.623+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:13:39.622+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:13:39.623+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:13:39.655+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.213 seconds
[2022-12-28T01:14:11.625+0000] {processor.py:156} INFO - Started process (PID=575) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:14:11.628+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:14:11.630+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:14:11.629+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:14:25.077+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:14:25.076+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:14:25.077+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:14:25.119+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 13.502 seconds
[2022-12-28T01:14:55.334+0000] {processor.py:156} INFO - Started process (PID=688) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:14:55.335+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:14:55.335+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:14:55.335+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:15:07.895+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:15:07.894+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:15:07.895+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:15:07.932+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.601 seconds
[2022-12-28T01:15:38.455+0000] {processor.py:156} INFO - Started process (PID=797) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:15:38.465+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:15:38.467+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:15:38.466+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:15:56.363+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:15:56.355+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:15:56.364+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:15:56.458+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 18.008 seconds
[2022-12-28T01:16:28.426+0000] {processor.py:156} INFO - Started process (PID=906) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:16:28.434+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:16:28.436+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:16:28.435+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:16:53.002+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:16:52.996+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:16:53.004+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:16:53.082+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 24.682 seconds
[2022-12-28T01:17:25.577+0000] {processor.py:156} INFO - Started process (PID=1038) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:17:25.577+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:17:25.578+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:17:25.578+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:17:44.315+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:17:44.314+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:17:44.316+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:17:44.366+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 18.793 seconds
[2022-12-28T01:18:15.050+0000] {processor.py:156} INFO - Started process (PID=1149) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:18:15.057+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:18:15.058+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:18:15.057+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:18:33.127+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:18:33.124+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:18:33.128+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:18:33.172+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 18.128 seconds
[2022-12-28T01:19:03.835+0000] {processor.py:156} INFO - Started process (PID=1258) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:19:03.846+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:19:03.847+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:19:03.846+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:19:16.823+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:19:16.821+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:19:16.824+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:19:16.861+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 13.035 seconds
[2022-12-28T01:19:47.647+0000] {processor.py:156} INFO - Started process (PID=1390) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:19:47.649+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:19:47.651+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:19:47.650+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:20:00.225+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:20:00.224+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:20:00.226+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:20:00.257+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.617 seconds
[2022-12-28T01:20:31.093+0000] {processor.py:156} INFO - Started process (PID=1501) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:20:31.095+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:20:31.097+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:20:31.097+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:20:42.912+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:20:42.910+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:20:42.912+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:20:42.953+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.870 seconds
[2022-12-28T01:21:13.708+0000] {processor.py:156} INFO - Started process (PID=1610) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:21:13.718+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:21:13.719+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:21:13.718+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:21:26.136+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:21:26.133+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:21:26.136+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:21:26.192+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.487 seconds
[2022-12-28T01:21:56.802+0000] {processor.py:156} INFO - Started process (PID=1742) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:21:56.804+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:21:56.806+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:21:56.806+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:22:09.452+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:22:09.449+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:22:09.452+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:22:09.487+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.693 seconds
[2022-12-28T01:22:40.406+0000] {processor.py:156} INFO - Started process (PID=1853) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:22:40.407+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:22:40.408+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:22:40.407+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:22:51.890+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:22:51.889+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:22:51.890+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:22:51.924+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.524 seconds
[2022-12-28T01:23:22.707+0000] {processor.py:156} INFO - Started process (PID=1962) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:23:22.717+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:23:22.718+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:23:22.717+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:23:34.784+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:23:34.783+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:23:34.785+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:23:34.816+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.112 seconds
[2022-12-28T01:24:05.799+0000] {processor.py:156} INFO - Started process (PID=2073) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:05.800+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:24:05.801+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:24:05.800+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:17.093+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:24:17.092+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:24:17.093+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:17.124+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.330 seconds
[2022-12-28T01:24:47.434+0000] {processor.py:156} INFO - Started process (PID=2205) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:47.445+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:24:47.446+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:24:47.446+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:59.284+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:24:59.283+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:24:59.285+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:24:59.315+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.889 seconds
[2022-12-28T01:25:30.166+0000] {processor.py:156} INFO - Started process (PID=2314) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:25:30.176+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:25:30.177+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:25:30.177+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:25:40.367+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:25:40.364+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:25:40.367+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:25:40.399+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 10.236 seconds
[2022-12-28T01:26:13.500+0000] {processor.py:156} INFO - Started process (PID=2425) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:26:13.501+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:26:13.501+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:26:13.501+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:26:25.924+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:26:25.923+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:26:25.924+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:26:25.956+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.460 seconds
[2022-12-28T01:26:57.479+0000] {processor.py:156} INFO - Started process (PID=2555) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:26:57.489+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:26:57.490+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:26:57.489+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:27:09.627+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:27:09.626+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:27:09.628+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:27:09.659+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.185 seconds
[2022-12-28T01:27:40.126+0000] {processor.py:156} INFO - Started process (PID=2666) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:27:40.136+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:27:40.136+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:27:40.136+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:27:52.836+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:27:52.834+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:27:52.837+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:27:52.900+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.777 seconds
[2022-12-28T01:28:23.122+0000] {processor.py:156} INFO - Started process (PID=2777) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:28:23.134+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:28:23.136+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:28:23.136+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:28:36.690+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:28:36.685+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:28:36.691+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:28:36.742+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 13.630 seconds
[2022-12-28T01:29:07.300+0000] {processor.py:156} INFO - Started process (PID=2886) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:29:07.310+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:29:07.311+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:29:07.310+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:29:25.192+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:29:25.190+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:29:25.193+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:29:25.253+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 17.956 seconds
[2022-12-28T01:30:02.575+0000] {processor.py:156} INFO - Started process (PID=3018) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:30:02.577+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:30:02.578+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:30:02.578+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:30:26.572+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:30:26.570+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:30:26.573+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:30:26.610+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 24.044 seconds
[2022-12-28T01:30:56.776+0000] {processor.py:156} INFO - Started process (PID=3129) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:30:56.787+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:30:56.788+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:30:56.788+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:31:14.229+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:31:14.227+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:31:14.229+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:31:14.266+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 17.497 seconds
[2022-12-28T01:31:44.760+0000] {processor.py:156} INFO - Started process (PID=3238) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:31:44.772+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:31:44.774+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:31:44.774+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:32:04.601+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:32:04.597+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:32:04.602+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:32:04.646+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 19.894 seconds
[2022-12-28T01:32:35.476+0000] {processor.py:156} INFO - Started process (PID=3370) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:32:35.487+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:32:35.489+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:32:35.489+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:32:49.989+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:32:49.988+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:32:49.989+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:32:50.011+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 14.542 seconds
[2022-12-28T01:33:20.374+0000] {processor.py:156} INFO - Started process (PID=3481) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:33:20.375+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:33:20.376+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:33:20.376+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:33:32.690+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:33:32.688+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:33:32.690+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:33:32.712+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.342 seconds
[2022-12-28T01:34:02.976+0000] {processor.py:156} INFO - Started process (PID=3590) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:02.977+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:34:02.977+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:34:02.977+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:14.770+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:34:14.768+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:34:14.770+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:14.799+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 11.827 seconds
[2022-12-28T01:34:44.964+0000] {processor.py:156} INFO - Started process (PID=3722) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:44.965+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:34:44.966+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:34:44.965+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:57.397+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:34:57.395+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:34:57.397+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:34:57.428+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.468 seconds
[2022-12-28T01:35:27.953+0000] {processor.py:156} INFO - Started process (PID=3833) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:35:27.963+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:35:27.964+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:35:27.964+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:35:40.373+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:35:40.370+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/checking_in_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checking_in_local.py", line 340, in <module>
    for i, content in enumerate(list_of_docs):
NameError: name 'list_of_docs' is not defined
[2022-12-28T01:35:40.373+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:35:40.405+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/checking_in_local.py took 12.455 seconds
[2022-12-28T01:36:10.795+0000] {processor.py:156} INFO - Started process (PID=3942) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:36:10.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:36:10.805+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:36:10.804+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:38:26.367+0000] {processor.py:156} INFO - Started process (PID=4053) to work on /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:38:26.368+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/checking_in_local.py for tasks to queue
[2022-12-28T01:38:26.370+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:38:26.370+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/checking_in_local.py
[2022-12-28T01:38:29.707+0000] {logging_mixin.py:117} INFO - [2022-12-28T01:38:29.691+0000] {process_utils.py:256} INFO - Waiting up to 5 seconds for processes to exit...
